[package]
name = "testinsurapp_backend"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]


[dependencies]
candid = "0.9.6"
ic-cdk = "0.10.0"
ic-cdk-macros = "0.6.10"
ic-cdk-timers = "0.4.0"
serde = { version = "1.0", features = ["derive"] }
ic-ledger-types = "0.3.0"
