// @ts-nocheck
/* eslint-disable */
/* This file was generated by Unframer for Framer project 3e1392145a324442 "Ascension (copy)", do not edit manually */
"use client";

// virtual:hamburgar
import { Fragment as Fragment2 } from "react";
import { ContextProviders } from "unframer";

// /:https://framerusercontent.com/modules/otLlqimbhKj8eoXuWnQZ/j2Rempi9NyDc2NRUFmUA/UlGL24W2s.js
import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { addFonts, addPropertyControls, ControlType, cx, useActiveVariantCallback, useComponentViewport, useLocaleInfo, useVariantState, withCSS } from "unframer";
import { LayoutGroup, motion, MotionConfigContext } from "unframer";
import * as React from "react";
var cycleOrder = ["Yno5RZBLV", "mfKKECYD7"];
var serializationHash = "framer-O0JHk";
var variantClassNames = { mfKKECYD7: "framer-v-1dgpj7e", Yno5RZBLV: "framer-v-ywu0ig" };
function addPropertyOverrides(overrides, ...variants) {
  const nextOverrides = {};
  variants === null || variants === void 0 ? void 0 : variants.forEach((variant) => variant && Object.assign(nextOverrides, overrides[variant]));
  return nextOverrides;
}
var transition1 = { damping: 60, delay: 0, mass: 1, stiffness: 500, type: "spring" };
var Transition = ({ value, children }) => {
  const config = React.useContext(MotionConfigContext);
  const transition = value !== null && value !== void 0 ? value : config.transition;
  const contextValue = React.useMemo(() => ({ ...config, transition }), [JSON.stringify(transition)]);
  return /* @__PURE__ */ _jsx(MotionConfigContext.Provider, { value: contextValue, children });
};
var Variants = motion.create(React.Fragment);
var humanReadableVariantMap = { Close: "mfKKECYD7", Menu: "Yno5RZBLV" };
var getProps = ({ height, id, tap, width, ...props }) => {
  var _humanReadableVariantMap_props_variant, _ref;
  return { ...props, variant: (_ref = (_humanReadableVariantMap_props_variant = humanReadableVariantMap[props.variant]) !== null && _humanReadableVariantMap_props_variant !== void 0 ? _humanReadableVariantMap_props_variant : props.variant) !== null && _ref !== void 0 ? _ref : "Yno5RZBLV", vnCwfiSlw: tap !== null && tap !== void 0 ? tap : props.vnCwfiSlw };
};
var createLayoutDependency = (props, variants) => {
  if (props.layoutDependency) return variants.join("-") + props.layoutDependency;
  return variants.join("-");
};
var Component = /* @__PURE__ */ React.forwardRef(function(props, ref) {
  const { activeLocale, setLocale } = useLocaleInfo();
  const { style, className, layoutId, variant, vnCwfiSlw, ...restProps } = getProps(props);
  const { baseVariant, classNames, clearLoadingGesture, gestureHandlers, gestureVariant, isLoading, setGestureState, setVariant, variants } = useVariantState({ cycleOrder, defaultVariant: "Yno5RZBLV", variant, variantClassNames });
  const layoutDependency = createLayoutDependency(props, variants);
  const { activeVariantCallback, delay } = useActiveVariantCallback(baseVariant);
  const onTap16f7gog = activeVariantCallback(async (...args) => {
    setGestureState({ isPressed: false });
    if (vnCwfiSlw) {
      const res = await vnCwfiSlw(...args);
      if (res === false) return false;
    }
  });
  const ref1 = React.useRef(null);
  const defaultLayoutId = React.useId();
  const sharedStyleClassNames = [];
  const componentViewport = useComponentViewport();
  return /* @__PURE__ */ _jsx(LayoutGroup, { id: layoutId !== null && layoutId !== void 0 ? layoutId : defaultLayoutId, children: /* @__PURE__ */ _jsx(Variants, { animate: variants, initial: false, children: /* @__PURE__ */ _jsx(Transition, { value: transition1, children: /* @__PURE__ */ _jsxs(motion.div, { ...restProps, ...gestureHandlers, className: cx(serializationHash, ...sharedStyleClassNames, "framer-ywu0ig", className, classNames), "data-framer-name": "Menu", "data-highlight": true, layoutDependency, layoutId: "Yno5RZBLV", onTap: onTap16f7gog, ref: ref !== null && ref !== void 0 ? ref : ref1, style: { ...style }, ...addPropertyOverrides({ mfKKECYD7: { "data-framer-name": "Close" } }, baseVariant, gestureVariant), children: [/* @__PURE__ */ _jsx(motion.div, { className: "framer-nalx34", "data-framer-name": "Bottom", layoutDependency, layoutId: "Yw8loTYvS", style: { backgroundColor: "rgb(255, 255, 255)", borderBottomLeftRadius: 10, borderBottomRightRadius: 10, borderTopLeftRadius: 10, borderTopRightRadius: 10, rotate: 0 }, variants: { mfKKECYD7: { rotate: -20 } } }), /* @__PURE__ */ _jsx(motion.div, { className: "framer-1bbgs9d", "data-framer-name": "Top", layoutDependency, layoutId: "Kb1ATLN5u", style: { backgroundColor: "rgb(255, 255, 255)", borderBottomLeftRadius: 10, borderBottomRightRadius: 10, borderTopLeftRadius: 10, borderTopRightRadius: 10, rotate: 0 }, variants: { mfKKECYD7: { rotate: 20 } } })] }) }) }) });
});
var css = ["@supports (aspect-ratio: 1) { body { --framer-aspect-ratio-supported: auto; } }", ".framer-O0JHk.framer-u6jsaz, .framer-O0JHk .framer-u6jsaz { display: block; }", ".framer-O0JHk.framer-ywu0ig { cursor: pointer; height: 40px; overflow: hidden; position: relative; width: 54px; }", ".framer-O0JHk .framer-nalx34 { flex: none; height: 2px; left: calc(50.00000000000002% - 36px / 2); overflow: hidden; position: absolute; top: calc(62.50000000000002% - 2px / 2); width: 36px; will-change: var(--framer-will-change-override, transform); }", ".framer-O0JHk .framer-1bbgs9d { flex: none; height: 2px; left: calc(50.00000000000002% - 36px / 2); overflow: hidden; position: absolute; top: calc(37.50000000000002% - 2px / 2); width: 36px; will-change: var(--framer-will-change-override, transform); }", ".framer-O0JHk.framer-v-1dgpj7e .framer-nalx34, .framer-O0JHk.framer-v-1dgpj7e .framer-1bbgs9d { top: calc(50.00000000000002% - 2px / 2); }"];
var FramerUlGL24W2s = withCSS(Component, css, "framer-O0JHk");
var stdin_default = FramerUlGL24W2s;
FramerUlGL24W2s.displayName = "Hamburgar";
FramerUlGL24W2s.defaultProps = { height: 40, width: 54 };
addPropertyControls(FramerUlGL24W2s, { variant: { options: ["Yno5RZBLV", "mfKKECYD7"], optionTitles: ["Menu", "Close"], title: "Variant", type: ControlType.Enum }, vnCwfiSlw: { title: "Tap", type: ControlType.EventHandler } });
addFonts(FramerUlGL24W2s, [{ explicitInter: true, fonts: [] }], { supportsExplicitInterCodegen: true });

// virtual:hamburgar
import { WithFramerBreakpoints } from "unframer";
import { jsx } from "react/jsx-runtime";
var locales = [];
var defaultResponsiveVariants = {
  "base": "mfKKECYD7",
  "xl": "Yno5RZBLV"
};
stdin_default.Responsive = ({ locale, ...rest }) => {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: { "augiA20Il": { "path": "/" }, "lJ4y2aXnc": { "path": "/404" } },
      children: /* @__PURE__ */ jsx(
        WithFramerBreakpoints,
        {
          Component: stdin_default,
          variants: defaultResponsiveVariants,
          ...rest
        }
      ),
      framerSiteId: "3e1392145a3244424045c47fd53de6285395b5d7c06ada8a31500d2d9adcfb4c",
      locale,
      locales
    }
  );
};
function ComponentWithRoot({ locale, ...rest }) {
  return /* @__PURE__ */ jsx(
    ContextProviders,
    {
      routes: {
        "augiA20Il": {
          "path": "/"
        },
        "lJ4y2aXnc": {
          "path": "/404"
        }
      },
      children: /* @__PURE__ */ jsx(stdin_default, { ...rest }),
      framerSiteId: "3e1392145a3244424045c47fd53de6285395b5d7c06ada8a31500d2d9adcfb4c",
      locale,
      locales
    }
  );
}
Object.assign(ComponentWithRoot, stdin_default);
export {
  ComponentWithRoot as default
};
